### ISSUE TITLE
Invalid versioning

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-accordion#13]
Similarly to [modal](https://github.com/interactive-pioneers/iptools-jquery-modal/commits/jquery1) the versioning has been incorrectly done. jQuery 2 upgrade was released in a minor which breaks all projects depending on minor `0.x.x` versions. It should have gone into `1.0.0` to note a breaking change as by [semver](http://semver.org) that is used in Bower.

Therefore:
- jQuery 1 development will continue on `jquery1` branch, in the range of `<1.0.0`
- jQuery 2 development will continue on `master` branch, in the range of `>=1.0.0`

**Comment by ain** [comment]
@GeorgMeyer23 @davleh @beroes please make sure that your projects will not automatically roll on to `0.3.0` that will run on jQuery 1 and break your jQuery 2 based project(s).

**Comment by davleh** [comment]
I did not change the versioning here. I would suggest to define a greater than condition for the version (as i already did on iptools-jquery-tooltip), just greater than 1.11.2! Accordion and tooltip work with both versions, so there is no need to have 2 branches!

**Comment by davleh** [comment]
Changed bower jquery dependency to >=1.11.3
