### ISSUE TITLE
Missing stop() statement before slideDown() and slideUp()

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-accordion#16]
What happens:
- if you click multiple times on the trigger the accordion opens/closes repeatedly.

What should happen:
- If you click on the trigger the current animation should be stopped and the triggered state should animate.

Hint:
- Add a stop() statement before using jQuery animation like slideDown() or slideUp().

**Comment by ain** [comment]
Is this a regression?

**Comment by GeorgMeyer23** [comment]
I don't know, current behaviour feels buggy :(

**Comment by GeorgMeyer23** [comment]
no regression, simple bug.

**Comment by GeorgMeyer23** [comment]
@davleh pls do a quick review, only minor fix, so no PR
