### ISSUE TITLE
Improve code / performance

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-accordion#4]
In method `toggle` `$panel` and `$content` are defined as variable. Since they both are static from the beginning assign them once as object property and refer to these.

I would suggest to bind them in `init` method.

``` javascript
this.$panel = $target.closest('.' + this.settings.panelClass);
this.$content = $panel.find('.' + this.settings.contentClass);
```

same thing for:

``` javascript
var panelActiveClass = self.settings.panelClass + self.settings.activeModifier;
```

**Comment by davleh** [comment]
``` javascript
this.$panel = $target.closest('.' + this.settings.panelClass);
this.$content = $panel.find('.' + this.settings.contentClass);
```

Can't be cached, because the are dependent on the specific event target.

**Comment by davleh** [comment]
Panel active class can now be passed with the options.
